---
name: common test

"on":
  push:
    branches:
      - main
    paths-ignore:
      - README*
      - LICENSE
      - '**.md'
      - '**.adoc'
  pull_request:
    paths-ignore:
      - README*
      - LICENSE
      - '**.md'
      - '**.adoc'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          config_file: .yamllint.yml
